### PR TITLE
Add Apache 2.0 LICENSE

### PR DESCRIPTION
**Pull request by natsukagami**
Same one as in https://github.com/scala/scala3

### CODE REVIEW

**Comment by natsukagami** [comment]
@belamenso @m8nmueller @odersky @He-Pin @SethTisue @2m @felixonmars 
Hello gears contributors, 
I am mentioning you in this PR because we want to add an open source license to the repo, which will grant rights as written in the LICENSE file to all code in the repository, including yours (which right now are under copyright). 
Please leave an indication of your agreement (a comment saying so, a thumbs-up reaction to this message) if you are okay with the Apache 2.0 license (which is the same as Dotty/scala3's). If you have questions or other objections, please feel free to do so in this PR.
Thank you!

**Comment by He-Pin** [comment]
@nicolasstucki I'm totally OK, go ahead.

**Comment by belamenso** [comment]
Regarding my contributions, I approve.

**Comment by natsukagami** [comment]
Thanks everyone!

**Pull request merged**
